/* eslint no-unused-vars: ["error", { "varsIgnorePattern": "(FRECENCY_PREFS)" }]*/

const FRECENCY_PREFS = [
  "firstBucketCutoff",
  "secondBucketCutoff",
  "thirdBucketCutoff",
  "fourthBucketCutoff",
  "firstBucketWeight",
  "secondBucketWeight",
  "thirdBucketWeight",
  "fourthBucketWeight",
  "defaultBucketWeight",
  "embedVisitBonus",
  "framedLinkVisitBonus",
  "linkVisitBonus",
  "typedVisitBonus",
  "bookmarkVisitBonus",
  "downloadVisitBonus",
  "permRedirectVisitBonus",
  "tempRedirectVisitBonus",
  "redirectSourceVisitBonus",
  "defaultVisitBonus",
  "unvisitedBookmarkBonus",
  "unvisitedTypedBonus",
  "reloadVisitBonus",
];
